name: Advance Workflow CI

on:
  push:
    branches: [ main ]

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Set up job
        run: echo "Starting Advance Pipeline..."

      - name: Run actions/checkout@v4
        uses: actions/checkout@v4

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Check Env
        run: python --version

      - name: Install dependencies
        run: |
          pip install mlflow dagshub pandas scikit-learn matplotlib

      - name: Run mlflow project
        # Memastikan mlflow berjalan di lingkungan lokal agar mlruns tercipta di root runner
        run: |
          mlflow run MLProject/ --env-manager local

      - name: Get latest MLflow run_id
        # Mencari folder UUID terbaru di mlruns/0 agar path build-docker tidak kosong
        run: |
          LATEST_RUN=$(ls -t mlruns/0 | grep -v "meta.yaml" | head -n 1)
          echo "RUN_ID=$LATEST_RUN" >> $GITHUB_ENV
          echo "Ditemukan ID Model: $LATEST_RUN"

      - name: Install Python dependencies
        run: pip install --upgrade pip
        
      - name: Upload to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: |
            mlruns/
            MLProject/mlruns/
            
      - name: Build Docker Model
        # Menggunakan BASE_DIR dan RUN_ID yang divalidasi dari langkah sebelumnya
        run: |
          mlflow models build-docker \
            -m "${{ env.BASE_DIR }}/${{ env.RUN_ID }}/artifacts/model" \
            -n "${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:latest" \
            --enable-mlserver     

      - name: Log in to Docker Hub
        # Login otomatis menggunakan Secrets yang sudah Anda buat
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Docker Image
        run: docker tag ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:latest ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:v1

      - name: Push Docker Image
        # Mengirim image model ke repositori Docker Hub 'dwisunartini'
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:latest

      - name: Post Set up Python 3.12.7
        run: echo "Done."

      - name: Complete job
        run: echo "Advance Workflow Finished! Model is on Docker Hub."
