name: Advance Workflow CI

on:
  push:
    branches: [ main ]

jobs:
  train:
    runs-on: ubuntu-latest
    steps:

      - name: Run actions/checkout@v4
        uses: actions/checkout@v4

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          pip install mlflow dagshub pandas scikit-learn matplotlib

      - name: Run mlflow project
        run: |
          # Jalankan mlflow dan pastikan mlruns tercipta di root
          mlflow run MLProject/ --env-manager local

      - name: Get latest MLflow run_id
        # Perbaikan pencarian folder UUID agar tidak kosong
        run: |
          # Cari folder UUID di root atau di dalam MLProject
          if [ -d "mlruns/0" ]; then 
            BASE_DIR="mlruns"
          else 
            BASE_DIR="MLProject/mlruns"
          fi
          LATEST_RUN=$(ls -t $BASE_DIR/0 | grep -v "meta.yaml" | head -n 1)
          echo "RUN_ID=$LATEST_RUN" >> $GITHUB_ENV
          echo "BASE_PATH=$BASE_DIR" >> $GITHUB_ENV
          echo "Ditemukan ID: $LATEST_RUN di folder: $BASE_DIR"

      - name: Install Python dependencies
        run: pip install --upgrade pip

      - name: Upload to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: |
            mlruns/
            MLProject/mlruns/

      - name: Build Docker Model
        # Menggunakan path hasil deteksi otomatis agar tidak error Errno 2
        run: |
          mlflow models build-docker \
            -m "${{ env.BASE_PATH }}/0/${{ env.RUN_ID }}/artifacts/model" \
            -n "${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:latest" \
            --enable-mlserver

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Docker Image
        run: docker tag ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:latest ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:v1

      - name: Push Docker Image
        # Mengirim ke Docker Hub dwisunartini
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:latest
