name: Advance Workflow CI

on:
  push:
    branches: [ main ]

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Set up job
        run: echo "Starting Advance Pipeline..."

      - name: Run actions/checkout@v4
        uses: actions/checkout@v4

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          pip install mlflow dagshub pandas scikit-learn matplotlib

      - name: Run mlflow project
        run: |
          # Jalankan training agar folder mlruns tercipta
          mlflow run MLProject/ --env-manager local

      - name: Get latest MLflow run_id
        # REVISI: Menggunakan pencarian wildcard untuk memastikan RUN_ID terisi
        run: |
          # Masuk ke folder mlruns/0 dan ambil nama folder pertama (UUID)
          ID=$(basename $(ls -d mlruns/0/*/ | head -n 1))
          echo "RUN_ID=$ID" >> $GITHUB_ENV
          echo "ID yang ditemukan: $ID"

      - name: Install Python dependencies
        run: pip install --upgrade pip

      - name: Upload to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: mlruns/

      - name: Build Docker Model
        # REVISI: Path divalidasi agar tidak ada double slash lagi
        run: |
          mlflow models build-docker \
            -m "mlruns/0/${{ env.RUN_ID }}/artifacts/model" \
            -n "${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:latest" \
            --enable-mlserver

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image
        # Mengirim ke Docker Hub dwisunartini
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:latest

      - name: Complete job
        run: echo "Advance Workflow Finished!"
