name: Advance Workflow CI

on:
  push:
    branches: [ main ]

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Set up job
        run: echo "Starting Advance Pipeline..."

      - name: Run actions/checkout@v4
        uses: actions/checkout@v4

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          pip install mlflow dagshub pandas scikit-learn matplotlib

      - name: Run mlflow project
        # PERBAIKAN: Memaksa penyimpanan ke folder lokal (sqlite) agar folder mlruns menetap
        run: |
          mlflow run MLProject/ --env-manager local --backend-config '{"use_conda": false}'

      - name: Get latest MLflow run_id
        # Sekarang folder mlruns pasti ada di root karena kita pakai tracking lokal
        run: |
          ID=$(ls -t mlruns/0 | grep -v "meta.yaml" | head -n 1)
          echo "RUN_ID=$ID" >> $GITHUB_ENV
          echo "Ditemukan ID: $ID"

      - name: Upload to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: mlruns/

      - name: Build Docker Model
        # Dengan RUN_ID yang sudah pasti terisi, build tidak akan error
        run: |
          mlflow models build-docker \
            -m "mlruns/0/${{ env.RUN_ID }}/artifacts/model" \
            -n "${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:latest" \
            --enable-mlserver

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image
        # Mengirim ke Docker Hub dwisunartini
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:latest

      - name: Complete job
        run: echo "Advance Workflow Finished!"
