name: Advance Workflow CI

on:
  push:
    branches: [ main ]

jobs:
  train:
    runs-on: ubuntu-latest
    steps:

      - name: Run actions/checkout@v4
        uses: actions/checkout@v4

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Check Env
        run: python --version

      - name: Install dependencies
        run: |
          pip install mlflow dagshub pandas scikit-learn matplotlib

      - name: Run mlflow project
        run: |
          mlflow run MLProject/ --env-manager local

      - name: Get latest MLflow run_id
        # PERBAIKAN: Mencari folder UUID terbaru di mlruns/0 agar RUN_ID tidak kosong
        run: |
          LATEST_RUN=$(ls -t mlruns/0 | grep -v "meta.yaml" | head -n 1)
          echo "RUN_ID=$LATEST_RUN" >> $GITHUB_ENV
          echo "Ditemukan ID: $LATEST_RUN"

      - name: Install Python dependencies
        run: pip install --upgrade pip

      - name: Upload to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: mlruns/

      - name: Build Docker Model
        # PERBAIKAN: Path model sekarang menggunakan RUN_ID yang sudah terdeteksi
        run: |
          mlflow models build-docker \
            -m "mlruns/0/${{ env.RUN_ID }}/artifacts/model" \
            -n "${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:latest" \
            --enable-mlserver

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Docker Image
        run: docker tag ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:latest ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:v1

      - name: Push Docker Image
        # Mengirim ke Docker Hub dwisunartini
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mlflow-model:latest
